In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\james\anaconda3\lib\site-packages (0.24.2)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\users\james\anaconda3\lib\site-packages (from pandas) (2.8.0)
Requirement already satisfied: numpy>=1.12.0 in c:\users\james\anaconda3\lib\site-packages (from pandas) (1.16.2)
Requirement already satisfied: pytz>=2011k in c:\users\james\anaconda3\lib\site-packages (from pandas) (2018.9)
Requirement already satisfied: six>=1.5 in c:\users\james\anaconda3\lib\site-packages (from python-dateutil>=2.5.0->pandas) (1.12.0)

In [2]:
import pandas as pd
import numpy as np
import requests # library to handle requests
import json # library to handle JSON files
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

!conda install -c conda-forge geopy --yes 
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

!pip install sklearn
from sklearn import linear_model

Collecting package metadata: ...working... done
Solving environment: ...working... done

# All requested packages already installed.

Requirement already satisfied: sklearn in c:\users\james\anaconda3\lib\site-packages (0.0)
Requirement already satisfied: scikit-learn in c:\users\james\anaconda3\lib\site-packages (from sklearn) (0.20.3)
Requirement already satisfied: scipy>=0.13.3 in c:\users\james\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.2.1)
Requirement already satisfied: numpy>=1.8.2 in c:\users\james\anaconda3\lib\site-packages (from scikit-learn->sklearn) (1.16.2)

In [21]:
#Pull UK house purchase price data. Limit to recent purchases in London.
min_date = "1+February+2019"
county = "LONDON"
csv_link = "http://landregistry.data.gov.uk/app/ppd/ppd_data.csv?county={}&et%5B%5D=lrcommon%3Afreehold&et%5B%5D=lrcommon%3Aleasehold&header=true&limit=all&min_date={}&nb%5B%5D=true&nb%5B%5D=false&ptype%5B%5D=lrcommon%3Adetached&ptype%5B%5D=lrcommon%3Asemi-detached&ptype%5B%5D=lrcommon%3Aterraced&ptype%5B%5D=lrcommon%3Aflat-maisonette&ptype%5B%5D=lrcommon%3AotherPropertyType&tc%5B%5D=ppd%3AstandardPricePaidTransaction&tc%5B%5D=ppd%3AadditionalPricePaidTransaction".format(county, min_date)

df = pd.read_csv(csv_link, header=None)

#Update column headers
headers = ['unique_id','price_paid','deed_date','postcode','property_type','new_build','estate_type','saon','paon','street','locality','town','district','county','transaction_category','linked_data_uri']
df.columns = headers

print(df.shape)

(2308, 16)

In [23]:
#Limit to flats purchased in London, that are not new builds

df = df[df['transaction_category']=='A']
df = df[df['property_type']=='F']
df = df[df['new_build']=='N']
#df = df[df['county']=='GREATER LONDON']

#Drop unwanted columns
df.drop(columns=['unique_id','deed_date', 'property_type', 'new_build','estate_type','saon','paon','locality','district','transaction_category','linked_data_uri'], inplace=True)

#Drop duplicate postcodes
df.drop_duplicates(subset=['postcode'], inplace=True)

#df = df[0:5]

print(df.shape)
df.head()

(777, 5)

    price_paid postcode           street     town          county
5       240000  BR1 3AG   FREELANDS ROAD  BROMLEY  GREATER LONDON
6       315000  BR1 3AX     WIDMORE ROAD  BROMLEY  GREATER LONDON
13      280000  BR1 3TY    OAKLANDS ROAD  BROMLEY  GREATER LONDON
24      200000  BR2 0AB     BROMLEY ROAD  BROMLEY  GREATER LONDON
25      280000  BR2 0JW  BECKENHAM GROVE  BROMLEY  GREATER LONDON

In [24]:
#Add lontitude and lattitude data
addresses = df['postcode']
latitude = []
longitude = []

for address in addresses:
    geolocator = Nominatim(user_agent="ny_explorer")
    location = geolocator.geocode(address+", UK", timeout=2)
    try:
        latitude.append(location.latitude)
        longitude.append(location.longitude)
    except:
        latitude.append(0)
        longitude.append(0)
        
df['Latitude']= latitude
df['Longitude']= longitude

In [25]:
#remove regions that location information was not available
df = df[(df['Latitude']!=0)| (df['Longitude']!=0)]

#df.head(10)
print(df.shape[0])

769

In [26]:
#Foursquare credentials
CLIENT_ID = 'QKP4KVQQZPVXMOKNIXHGQAT1E2IJZCHQPFB4XJGP3MC0CFUO' # your Foursquare ID
CLIENT_SECRET = '1N5BIRBR1EA5CO1QFMNHU1241SOFM5KJLLQRJGMDC0NOYWPH' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version
LIMIT = 200 # limit of number of venues returned by Foursquare API
radius = 100 # define radius
categoryId = ''

In [27]:
#What are the most popular places nearby?

def getNearbyVenues(names, latitudes, longitudes, avg_price, radius=100):
   
    region_list = []
    price_list = []
    
    for name, lat, lng, price in zip(names, latitudes, longitudes, avg_price):
                    
        # create the API request URL
        #url = 'https://api.foursquare.com/v2/venues/search?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
        url = 'https://api.foursquare.com/v2/venues/search?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}&categoryId={}'.format(    
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT,
            categoryId)
        
        #print(url) 
        
        # make the GET request
        results = requests.get(url).json()["response"]
        
        #flatten JSON file
        resultsVen = json_normalize(results['venues'])
        resultsCat = json_normalize(data=results['venues'], record_path=['categories'], record_prefix='cat_', errors='ignore')
        resultsVenCat = pd.concat([resultsVen, resultsCat], axis=1)
        resultsVenCat = resultsVenCat[['name','location.distance','location.formattedAddress','location.lat','location.lng','cat_name']]
               
        #Add region name and average price 
        for i in range(0,resultsVen.shape[0]):
            region_list.append(name)
            price_list.append(price)
        
        region_list = pd.DataFrame(region_list, columns=['Property Postcode'])
        price_list = pd.DataFrame(price_list, columns=['Property Price'])
        
        nearbyVenues = pd.concat([region_list, price_list, resultsVenCat], axis=1)

    return(nearbyVenues)

In [28]:
london_venues = pd.DataFrame()

#request venue information for each postcode
for region in df['postcode']:
    region_venues = df[df['postcode']==region]
    london_venues = london_venues.append((getNearbyVenues(names=region_venues['postcode'],
                                                  latitudes=region_venues['Latitude'],
                                                  longitudes=region_venues['Longitude'],
                                                  avg_price=region_venues['price_paid'],
                                                  radius=radius)),ignore_index=True)
    
#rename columns
london_venues.rename(columns={'name':'Venue Name',
                          'location.distance':'Venue Distance',
                          'location.formattedAddress':'Venue Address',
                          'location.lat':'Venue Lat',
                          'location.lng':'Venue Lng',
                          'cat_name':'Venue Category'}, inplace=True)

print(london_venues.shape)
london_venues.head()

,Property Postcode,Property Price,Venue Name,Venue Distance,Venue Address,Venue Lat,Venue Lng,Venue Category
0,BR1 3AG,240000,Village Stores,239,"[Bromley, Greater London, BR1 3HZ, United King...",51.410290,0.024560,Convenience Store
1,BR1 3AG,240000,wagamama,627,"[intu Shopping Centre (High St), Bromley, Grea...",51.404025,0.017960,Asian Restaurant
2,BR1 3AG,240000,Alan de Maid,622,"[The Old Municipal Buildings, 19 East Street, ...",51.406587,0.015505,Real Estate Office
3,BR1 3AG,240000,Sharps Bedrooms,499,"[24/30 Widmore Road, Bromley, Greater London, ...",51.406037,0.017762,Furniture / Home Store
4,BR1 3AG,240000,Coast,642,"[Unit 245 The Glades (High St), Bromley, Great...",51.404722,0.016671,Boutique

In [30]:
london_onehot = pd.get_dummies(london_venues[['Venue Category']], prefix="", prefix_sep="")
# add neighborhood column back to dataframe

london_onehot['Property Price'] = london_venues['Property Price'] 
london_onehot['Property Postcode'] = london_venues['Property Postcode'] 

#Reorder columns
fixed_columns = [london_onehot.columns[-1]] + [london_onehot.columns[-2]] + list(london_onehot.columns[:-2])
london_onehot = london_onehot[fixed_columns]

df1 = london_onehot.groupby(['Property Postcode','Property Price']).sum()
df1.reset_index(inplace=True)

print(df1.shape)
df1.head()

(769, 649)

,Property Postcode,Property Price,ATM,Accessories Store,Acupuncturist,Adult Boutique,Adult Education Center,Advertising Agency,Afghan Restaurant,African Restaurant,...,Whisky Bar,Windmill,Wine Bar,Wine Shop,Winery,Wings Joint,Women's Store,Xinjiang Restaurant,Yoga Studio,Zoo Exhibit
0,BR1 3AG,240000,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,4,0,0,0
1,BR1 3AX,315000,0,1,0,0,2,0,0,1,...,0,0,0,0,0,0,4,0,0,0
2,BR1 3TY,280000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,BR2 0AB,200000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,BR2 0JW,280000,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0

In [60]:
df1.sort_values(by=['Property Price'])

,Property Postcode,Property Price,ATM,Accessories Store,Acupuncturist,Adult Boutique,Adult Education Center,Advertising Agency,Afghan Restaurant,African Restaurant,...,Whisky Bar,Windmill,Wine Bar,Wine Shop,Winery,Wings Joint,Women's Store,Xinjiang Restaurant,Yoga Studio,Zoo Exhibit
11,BR2 9FN,87500,0,0,0,0,2,0,0,1,...,0,0,0,0,0,0,0,0,0,0
18,BR4 9QP,88000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
666,TW5 0PT,90000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32,CR0 2RU,92000,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
64,E1 1AQ,100000,0,0,0,0,0,2,0,1,...,0,0,0,0,0,1,2,0,0,0
115,E3 2SJ,100500,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
63,DA8 1SQ,102375,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
728,W3 7FG,108750,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
368,RM6 4YJ,110000,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
263,N4 2BP,110000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
82,E15 1EQ,111000,0,0,1,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
185,HA9 0HL,112000,0,2,0,0,1,0,0,1,...,0,0,0,0,0,0,1,0,0,0
53,DA15 7JU,115000,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
113,E3 2DB,117000,0,0,0,0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
570,SW18 4GS,118750,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
172,HA1 3RR,122000,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
562,SW18 1QS,122500,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
122,E3 5GQ,126000,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0
233,N13 5UP,128000,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
173,HA2 0ER,128000,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
377,SE10 0FF,130000,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
223,N1 7GQ,138750,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,0
344,NW7 1FY,140000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
467,SE3 9FF,140000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
186,HA9 6BF,145000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36,CR0 5QN,150000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33,CR0 2SQ,155000,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
412,SE16 2PY,157500,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
370,RM7 0DU,160000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
740,W5 3DL,160000,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
665,TW4 7PP,160000,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
10,BR2 8FF,160200,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
471,SE5 0BD,162000,0,0,0,0,0,0,0,3,...,0,0,0,0,0,1,1,0,0,0
389,SE11 4BN,165000,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
360,RM10 8UL,165000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
174,HA2 0FJ,165000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
417,SE16 5HB,170000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
683,UB3 2DH,170000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
188,IG11 9XE,172000,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
191,IG4 5EL,172500,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
363,RM13 8PP,174995,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
660,TW13 4TL,175000,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,3,0,0,0
190,IG2 7EQ,175000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
481,SE9 2TA,175000,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
535,SW15 4EH,175000,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
163,EN3 5XB,175000,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
83,E15 2GD,175000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
75,E14 3GS,175000,0,0,0,0,0,1,0,0,...,0,0,2,0,0,0,0,0,0,0
9,BR2 7LP,179000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
694,UB8 2RU,180000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,EC2Y 8NE,920000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
755,W9 1HD,922500,0,0,0,0,0,0,0,0,...,1,0,0,3,0,0,0,0,0,0
90,E16 2SJ,974000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
587,SW1W 8DT,985000,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
717,W1U 5BY,1000000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
615,SW4 0AP,1035000,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
303,NW1 6AN,1050000,0,0,0,0,0,0,0,0,...,1,0,1,1,0,0,0,0,1,0
713,W1H 2EP,1050000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
701,W11 3TG,1050000,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
463,SE3 0NZ,1069666,0,0,0,0,0,0,0,0,...,0,0,2,2,0,0,3,0,0,0
376,SE1 9NX,1150000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
346,NW8 6BX,1150000,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,2,0,1,2
323,NW3 3DP,1175000,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
214,N1 1PT,1185000,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,2,0
749,W8 4SA,1195000,0,0,0,0,0,0,0,0,...,0,0,2,1,0,0,0,0,1,0
588,SW1W 9DA,1225000,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,1,0
352,NW8 9NR,1227000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
621,SW5 0NJ,1246246,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
613,SW3 3PR,1275000,1,0,0,0,0,3,0,0,...,0,0,0,2,0,0,4,0,0,0
508,SW10 9NZ,1280000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,1,0
324,NW3 3NT,1338000,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
590,SW1X 9JX,1378000,0,2,0,0,0,0,0,0,...,0,0,1,0,0,0,2,0,0,0
349,NW8 8HU,1430000,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0
335,NW6 1JS,1530000,0,0,0,0,0,0,0,0,...,0,0,0,2,1,0,0,0,0,0
702,W11 4BE,1550000,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,5,0,0,0
614,SW3 3UB,1600000,0,1,1,0,0,0,0,0,...,0,0,0,0,1,0,8,0,0,0
515,SW11 8AE,1625000,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0
714,W1H 7LD,1650000,0,0,0,0,0,0,1,0,...,1,0,1,0,0,0,0,0,0,0
739,W4 5BW,1690000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
628,SW7 1LJ,1700000,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
350,NW8 8JR,1700000,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0
753,W8 5UF,1750000,0,0,0,0,0,0,0,0,...,0,0,0,4,0,0,0,0,0,0
656,TW10 6RN,1760000,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
302,NW1 5SU,1800000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
752,W8 5LS,1850000,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
620,SW5 0AZ,1850000,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
509,SW10 9QY,1900000,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,2,0,0,0
589,SW1X 0EA,2000000,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
715,W1J 5HG,2200000,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,0,0
699,W11 3BS,2300000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,7,0,0,0
750,W8 5EH,2320000,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
700,W11 3BW,2500000,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,5,0,0,0
698,W11 2LX,2515000,0,2,0,0,0,1,0,0,...,0,0,1,1,1,0,1,0,0,0
348,NW8 7RJ,2600000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
751,W8 5LB,2650000,0,1,0,0,0,0,0,0,...,0,0,0,5,0,0,0,0,0,0
710,W14 8JZ,2650000,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
581,SW19 7DN,2800000,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
630,SW7 3BJ,3075000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,0,0
629,SW7 1NL,3294000,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
767,WC2E 9DS,4967000,0,6,0,0,0,1,0,0,...,0,0,0,0,0,0,4,0,0,0

In [43]:
#Create dataframe of feature list
df_features = pd.DataFrame(df1.columns)
df_features = df_features.iloc[2:df1.shape[1], :]
df_features.reset_index(inplace=True)

In [57]:
regr = linear_model.LinearRegression()

#Set venues as features
x = df1.iloc[:, 2:df1.shape[1]]

#Set price as result(y)
y=df1[['Property Price']]

#Fit data
regr.fit(x, y)

#transpose feature coefficients and store in a dataframe
coefs = pd.DataFrame(regr.coef_).T

#Add feature labels and sort
df_coef = pd.concat([df_features, coefs],axis=1,ignore_index=True)
df_coef.drop(columns=0, inplace=True)
df_coef.rename(columns={1:'Venue Category',2:'Coefficient'}, inplace=True)
df_coef.sort_values(by=['Coefficient'],inplace=True)

#print ('Coefficients: ', regr.coef_)
print ('Intercept: ',regr.intercept_)

Intercept:  [445829.15646659]

In [58]:
pd.set_option('display.max_rows', 100)
df_coef['Coefficient'] = df_coef['Coefficient'].round(0)
df_coef

                Venue Category  Coefficient
342                 Laboratory   -3567550.0
483                    Rafting   -3012561.0
447                   Pet Café   -1297878.0
460                Planetarium   -1205528.0
152            College Stadium   -1134334.0
120                     Circus   -1079164.0
291                   Heliport   -1005282.0
389                  Monastery    -672697.0
84               Burrito Place    -563190.0
632                 Water Park    -538588.0
431                Outlet Mall    -520854.0
250                   Fountain    -508135.0
151       College Soccer Field    -500727.0
173                    Country    -500179.0
255         Frozen Yogurt Shop    -471785.0
594              Tour Provider    -470959.0
523         Shaanxi Restaurant    -468990.0
570                Swim School    -456716.0
396           Motorsports Shop    -438457.0
134   College Basketball Court    -425378.0
229                   Festival    -413154.0
109       Caucasian Restaurant    -404900.0
178                   Creperie    -404523.0
536              Smoothie Shop    -395738.0
471                Prayer Room    -388991.0
0                          ATM    -388854.0
279                  Gun Range    -384169.0
317      Indonesian Restaurant    -383495.0
55          Belgian Restaurant    -375360.0
355                 Lighthouse    -371364.0
644        Xinjiang Restaurant    -362544.0
313  Indian Chinese Restaurant    -361923.0
513                 Salsa Club    -355421.0
426        Outdoor Event Space    -336599.0
325                     Island    -332743.0
494             Rental Service    -327852.0
206                  Drugstore    -324059.0
10              Airport Lounge    -321203.0
196                 Distillery    -315499.0
3               Adult Boutique    -303025.0
434            Paintball Field    -302862.0
185                Dairy Store    -285693.0
8                      Airport    -273131.0
283                   Gym Pool    -272633.0
336               Kingdom Hall    -272507.0
362         Mac & Cheese Joint    -267810.0
415                     Notary    -267778.0
82        Bulgarian Restaurant    -267697.0
367           Maternity Clinic    -266630.0
541             Sorority House    -262361.0
..                         ...          ...
61                  Board Shop     271206.0
184               Cycle Studio     273246.0
480                    RV Park     275604.0
259                Gaming Cafe     276436.0
607         Travel & Transport     281741.0
49                       Beach     283973.0
322               Intersection     298527.0
626           Volleyball Court     303388.0
436                     Palace     315923.0
340          Kosher Restaurant     318801.0
31       Australian Restaurant     322346.0
338             Knitting Store     333231.0
48                Bathing Area     338428.0
142   College History Building     343227.0
615             Used Bookstore     345898.0
390       Mongolian Restaurant     349558.0
20      Argentinian Restaurant     356535.0
239              Fishing Store     360718.0
497                  Residence     389120.0
59                  Bike Trail     394850.0
32         Austrian Restaurant     400077.0
414    North Indian Restaurant     403712.0
491               Rehab Center     410513.0
180           Cuban Restaurant     420585.0
12            Airport Terminal     424409.0
509         Russian Restaurant     432389.0
99                       Canal     461626.0
323           Iraqi Restaurant     476270.0
170      Corporate Coffee Shop     483690.0
167             Cooking School     485704.0
268          German Restaurant     519667.0
636                       Well     526554.0
67            Botanical Garden     574422.0
394                      Motel     585751.0
503         Rock Climbing Spot     602776.0
566                Summer Camp     683022.0
95        Cambodian Restaurant     707596.0
542                 Soup Place     708074.0
419                Opera House     724133.0
273         Golf Driving Range     772165.0
495           Research Station     793818.0
154       College Tennis Court     812523.0
546              Souvenir Shop     817463.0
520        Scottish Restaurant     955201.0
224                       Fair     989014.0
326         Israeli Restaurant    1096253.0
9                 Airport Gate    1195566.0
277    Grilled Meat Restaurant    1357091.0
139      College Cricket Pitch    1477161.0
47                  Bath House    1958829.0

[647 rows x 2 columns]